name: C++ CI Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with g++
        run: |
          g++ -std=c++17 -O2 main.cpp -o test_exec
          ./test_exec || ./test_exec.exe
